---
title: "R Neurohacking Part 14"
author: "Vicky Wong"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library

```{r}
#library
library(devtools)
library(oro.dicom)
library(oro.nifti)
library(AnalyzeFMRI)
library(fslr)
library(scales)
library(ggplot2)
library(reshape2)
```

File Path

```{r}
#file paths
win_file_113_01_MPRAGE <- "C:/R_Neurohacking_Data/kirby21/visit_1/113/113-01-MPRAGE.nii.gz"
wsl_file_113_01_MPRAGE <- "/mnt/c/R_Neurohacking_Data/kirby21/visit_1/113/113-01-MPRAGE.nii.gz"
```

Statistics for 113-01-MPRAGE.nii.gz

```{r}
#read original MPRAGE image
nim_113_01_MPRAGE <- readNIfTI(win_file_113_01_MPRAGE)

#compute mean
mean_val_113_01_MPRAGE <- mean(nim_113_01_MPRAGE)
mean_text_113_01_MPRAGE <- paste0("113-01-MPRAGE.nii.gz Mean: ", round(mean_val_113_01_MPRAGE, 2))

#save mean as PNG
png("113-01-MPRAGE_Mean.png", width = 800, height = 800)
plot.new()
text(0.5, 0.5, mean_text_113_01_MPRAGE, cex = 3)
dev.off()
```

Statistics for 113-02-MPRAGE.nii.gz

```{r}
#file paths
win_file_113_02_MPRAGE <- "C:/R_Neurohacking_Data/kirby21/visit_2/113/113-02-MPRAGE.nii.gz"
wsl_file_113_02_MPRAGE <- "/mnt/c/R_Neurohacking_Data/kirby21/visit_2/113/113-02-MPRAGE.nii.gz"

#read original MPRAGE image
nim_113_02_MPRAGE <- readNIfTI(win_file_113_02_MPRAGE)

#compute mean
mean_val_113_02_MPRAGE <- mean(nim_113_02_MPRAGE)
mean_text_113_02_MPRAGE <- paste0("113-02-MPRAGE.nii.gz Mean: ", round(mean_val_113_02_MPRAGE, 2))

#save mean as PNG
png("113-02-MPRAGE_Mean.png", width = 800, height = 800)
plot.new()
text(0.5, 0.5, mean_text_113_02_MPRAGE, cex = 3)
dev.off()
```

Bias Field Correction Using FSLR for 113-01-MPRAGE.nii.gz and 113-02-MPRAGE.nii.gz

```{r}
#run FSL fast -B via WSL for 113-01-MPRAGE
system(paste("wsl fast -B", shQuote(wsl_file_113_01_MPRAGE)))

#run FSL fast -B via WSL for 113-02-MPRAGE
system(paste("wsl fast -B", shQuote(wsl_file_113_02_MPRAGE)))

# Read bias-corrected MPRAGE images
fast_img_113_01_MPRAGE <- readNIfTI("C:/R_Neurohacking_Data/kirby21/visit_1/113/113-01-MPRAGE.nii.gz")
fast_img_113_02_MPRAGE <- readNIfTI("C:/R_Neurohacking_Data/kirby21/visit_2/113/113-02-MPRAGE.nii.gz")
```

Plotting the Results in R 113-01-MPRAGE.nii.gz and 113-02-MPRAGE.nii.gz

```{r}
#diverging color palettes
fcol1 <- div_gradient_pal(low="blue", mid="yellow", high="red")
fcol2 <- div_gradient_pal(low="blue", mid="yellow", high="red")

#113-01-MPRAGE difference image
sub_bias_113_01_MPRAGE <- nim_113_01_MPRAGE - fast_img_113_01_MPRAGE
q1 <- quantile(sub_bias_113_01_MPRAGE[sub_bias_113_01_MPRAGE != 0], probs = seq(0,1,by=0.1))

#save 113-01-MPRAGE plot as PNG
png("113-01-MPRAGE_Difference.png", width=800, height=800)
if(any(sub_bias_113_01_MPRAGE != 0)){
  ortho2(
    nim_113_01_MPRAGE,
    sub_bias_113_01_MPRAGE,
    col.y = alpha(fcol1(seq(0,1,length.out=10)), 0.5),
    ybreaks = q1,
    ycolorbar = TRUE,
    text = "113-01-MPRAGE:\nOriginal Minus Bias-Corrected",
    cex = 0.7
  )
} else {
  ortho2(
    nim_113_01_MPRAGE,
    text = "113-01-MPRAGE.nii.gz:\nOriginal Image (No Difference)",
    cex = 0.7
  )
}
dev.off()

#113-02-MPRAGE difference image
sub_bias_113_02_MPRAGE <- nim_113_02_MPRAGE - fast_img_113_02_MPRAGE
q2 <- quantile(sub_bias_113_02_MPRAGE[sub_bias_113_02_MPRAGE != 0], probs = seq(0,1,by=0.1))

#save 113-02-MPRAGE plot as PNG
png("113-02-MPRAGE_Difference.png", width=800, height=800)
if(any(sub_bias_113_02_MPRAGE != 0)){
  ortho2(
    nim_113_02_MPRAGE,
    sub_bias_113_02_MPRAGE,
    col.y = alpha(fcol2(seq(0,1,length.out=10)), 0.5),
    ybreaks = q2,
    ycolorbar = TRUE,
    text = "113-02-MPRAGE:\nOriginal Minus Bias-Corrected",
    cex = 0.7
  )
} else {
  ortho2(
    nim_113_02_MPRAGE,
    text = "113-02-MPRAGE.nii.gz:\nOriginal Image (No Difference)",
    cex = 0.7
  )
}
dev.off()
```

Plotting Histogram Slices 02, 06, 10, 14, 18, 22

```{r}           
#slices to plot
slices_02_06_10_14_18_22 <- c(2, 6, 10, 14, 18, 22)

#113-01-MPRAGE histogram slices 02, 06, 10, 14, 18, 22
vals_113_01_MPRAGE <- lapply(slices_02_06_10_14_18_22, function(x) {
  data.frame(
    Original = c(nim_113_01_MPRAGE[,,x]),
    BiasCorrected = c(fast_img_113_01_MPRAGE[,,x]),
    slice = x
  )
})
vals_113_01_MPRAGE <- do.call(rbind, vals_113_01_MPRAGE)
v_113_01_MPRAGE <- melt(vals_113_01_MPRAGE, id.vars="slice", variable.name="ImageType", value.name="Value")

png("113_01_MPRAGE_Slices_02_06_10_14_18_22_Histogram.png", width=1200, height=600)
g_113_01_MPRAGE <- ggplot(v_113_01_MPRAGE, aes(x=Value, colour=factor(slice))) +
  geom_density() +
  facet_wrap(~ImageType) +
  scale_colour_discrete(name="Slice #") +
  theme_minimal() +
  theme(plot.title = element_text(size=16)) +
  ggtitle("Histogram of Original vs Bias-Corrected Values: 113-01-MPRAGE.nii.gz (Slices 02, 06, 10, 14, 18, 22)")
print(g_113_01_MPRAGE)
dev.off()

#113-02-MPRAGE histogram slices 02, 06, 10, 14, 18, 22
vals_113_02_MPRAGE <- lapply(slices_02_06_10_14_18_22, function(x) {
  data.frame(
    Original = c(nim_113_02_MPRAGE[,,x]),
    BiasCorrected = c(fast_img_113_02_MPRAGE[,,x]),
    slice = x
  )
})
vals_113_02_MPRAGE <- do.call(rbind, vals_113_02_MPRAGE)
v_113_02_MPRAGE <- melt(vals_113_02_MPRAGE, id.vars="slice", variable.name="ImageType", value.name="Value")

png("113_02_MPRAGE_Slices_02_06_10_14_18_22_Histogram.png", width=1200, height=600)
g_113_02_MPRAGE <- ggplot(v_113_02_MPRAGE, aes(x=Value, colour=factor(slice))) +
  geom_density() +
  facet_wrap(~ImageType) +
  scale_colour_discrete(name="Slice #") +
  theme_minimal() +
  theme(plot.title = element_text(size=16)) +
  ggtitle("Histogram of Original vs Bias-Corrected Values: 113-02-MPRAGE.nii.gz (Slices 02, 06, 10, 14, 18, 22)")
print(g_113_02_MPRAGE)
dev.off()
```

Plotting Histogram Slices 01-22

```{r}
#slices to plot
slices_01_22 <- 1:22

#113-01-MPRAGE histogram slices 01-22
vals_113_01_MPRAGE <- lapply(slices_01_22, function(x) {
  data.frame(
    Original = c(nim_113_01_MPRAGE[,,x]),
    BiasCorrected = c(fast_img_113_01_MPRAGE[,,x]),
    slice = x
  )
})
vals_113_01_MPRAGE <- do.call(rbind, vals_113_01_MPRAGE)
v_113_01_MPRAGE <- melt(vals_113_01_MPRAGE, id.vars="slice", variable.name="ImageType", value.name="Value")

png("113_01_MPRAGE_Slices_01_22_Histogram.png", width=1200, height=600)
g_113_01_MPRAGE <- ggplot(v_113_01_MPRAGE, aes(x=Value, colour=factor(slice))) +
  geom_density() +
  facet_wrap(~ImageType) +
  scale_colour_discrete(name="Slice #") +
  theme_minimal() +
  theme(plot.title = element_text(size=16)) +
  ggtitle("Histogram of Original vs Bias-Corrected Values: 113-01-MPRAGE.nii.gz (Slices 01-22)")
print(g_113_01_MPRAGE)
dev.off()

#113-02-MPRAGE histogram slices 01-22
vals_113_02_MPRAGE <- lapply(slices_01_22, function(x) {
  data.frame(
    Original = c(nim_113_02_MPRAGE[,,x]),
    BiasCorrected = c(fast_img_113_02_MPRAGE[,,x]),
    slice = x
  )
})
vals_113_02_MPRAGE <- do.call(rbind, vals_113_02_MPRAGE)
v_113_02_MPRAGE <- melt(vals_113_02_MPRAGE, id.vars="slice", variable.name="ImageType", value.name="Value")

png("113_02_MPRAGE_Slices_01_22_Histogram.png", width=1200, height=600)
g_113_02_MPRAGE <- ggplot(v_113_02_MPRAGE, aes(x=Value, colour=factor(slice))) +
  geom_density() +
  facet_wrap(~ImageType) +
  scale_colour_discrete(name="Slice #") +
  theme_minimal() +
  theme(plot.title = element_text(size=16)) +
  ggtitle("Histogram of Original vs Bias-Corrected Values: 113-02-MPRAGE.nii.gz (Slices 01-22)")
print(g_113_02_MPRAGE)
dev.off()
```